name: Feature request
description: Suggest an idea for Nativefier
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request 🙂! Help us help you, **fill this form thoroughly**. An incomplete feature request is a useless feature request.
  - type: checkboxes
    id: homework
    attributes:
      label: Homework
      options:
        - label: I took the time to write a good, descriptive issue title
          required: true
        - label: I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md), no existing option fits my needs.
          required: true
        - label: I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
          required: true
        - label: I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my feature request is new.
          required: true
        - label: I'm running the [latest version](https://github.com/nativefier/nativefier/releases). Yes, the feature I'm requesting isn't in it.
          required: true
    validations:
      required: true
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem statement
      description: A clear and concise description of what your feature would be.
      placeholder: |
        For example:
        Nativefier should XYZ, ... details details details...
        Existing option --something is not what I want, because ...
    validations:
      required: true
  - type: textarea
    id: motivation-and-context
    attributes:
      label: Motivation & context
      placeholder: |
        What makes you want this feature?
        Where does it come from?
    validations:
      required: true
